version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    restart: unless-stopped
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=localhost
      - KC_IMPORT=/opt/keycloak/data/import/realm-export.json
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    command: start-dev
    ports:
      - "8080:8080"

volumes:
  keycloak_data:
